#!/bin/bash

# PR Creator Hook
# Automatically creates a pull request from the current branch to the target
# base branch (default: main) at the end of a Copilot coding agent session.
#
# Environment variables:
#   PR_BASE_BRANCH   - Target base branch for the PR (default: main)
#   PR_TITLE         - PR title; defaults to the last git commit message
#   PR_BODY          - PR body text (default: auto-generated)
#   PR_DRAFT         - "true" to open as a draft PR (default: false)
#   SKIP_PR_CREATION - "true" to disable PR creation entirely (default: unset)

set -euo pipefail

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

log()  { echo "$*"; }
warn() { echo "⚠️  $*" >&2; }

# ---------------------------------------------------------------------------
# Guards
# ---------------------------------------------------------------------------

if [[ "${SKIP_PR_CREATION:-}" == "true" ]]; then
  log "⏭️  PR creation skipped (SKIP_PR_CREATION=true)"
  exit 0
fi

if ! command -v gh &>/dev/null; then
  warn "gh CLI not found — skipping PR creation."
  warn "Install the GitHub CLI (https://cli.github.com) and authenticate with 'gh auth login'."
  exit 0
fi

if ! git rev-parse --is-inside-work-tree &>/dev/null; then
  warn "Not in a git repository — skipping PR creation."
  exit 0
fi

# ---------------------------------------------------------------------------
# Determine current branch and base branch
# ---------------------------------------------------------------------------

CURRENT_BRANCH=$(git symbolic-ref --short HEAD 2>/dev/null || true)
if [[ -z "$CURRENT_BRANCH" ]]; then
  warn "Detached HEAD state detected — cannot create a PR."
  exit 0
fi

BASE_BRANCH="${PR_BASE_BRANCH:-main}"

if [[ "$CURRENT_BRANCH" == "$BASE_BRANCH" ]]; then
  warn "Current branch is already '$BASE_BRANCH' — no PR needed."
  exit 0
fi

# ---------------------------------------------------------------------------
# Ensure the current branch has at least one commit ahead of the base
# ---------------------------------------------------------------------------

AHEAD=$(git rev-list --count "origin/${BASE_BRANCH}...HEAD" 2>/dev/null \
        || git rev-list --count "${BASE_BRANCH}...HEAD" 2>/dev/null \
        || echo "0")

if [[ "$AHEAD" == "0" ]]; then
  log "ℹ️  No commits ahead of '${BASE_BRANCH}' — skipping PR creation."
  exit 0
fi

# ---------------------------------------------------------------------------
# Check for an existing open PR for this branch
# ---------------------------------------------------------------------------

EXISTING_PR_URL=$(gh pr list \
  --head "$CURRENT_BRANCH" \
  --base "$BASE_BRANCH" \
  --state open \
  --json url \
  --jq '.[0].url' 2>/dev/null || true)

if [[ -n "$EXISTING_PR_URL" && "$EXISTING_PR_URL" != "null" ]]; then
  log "ℹ️  An open PR already exists for '${CURRENT_BRANCH}' → '${BASE_BRANCH}': ${EXISTING_PR_URL}"
  exit 0
fi

# ---------------------------------------------------------------------------
# Build PR title and body
# ---------------------------------------------------------------------------

DEFAULT_TITLE=$(git log -1 --pretty=format="%s" 2>/dev/null || echo "Changes from ${CURRENT_BRANCH}")
PR_TITLE="${PR_TITLE:-$DEFAULT_TITLE}"

if [[ -z "${PR_BODY:-}" ]]; then
  COMMIT_COUNT=$(git rev-list --count "origin/${BASE_BRANCH}...HEAD" 2>/dev/null \
                 || git rev-list --count "${BASE_BRANCH}...HEAD" 2>/dev/null \
                 || echo "1")
  PR_BODY="$(cat <<EOF
This PR was automatically created by the Copilot PR Creator hook at the end of a coding session.

**Branch:** \`${CURRENT_BRANCH}\`
**Base:** \`${BASE_BRANCH}\`
**Commits ahead:** ${COMMIT_COUNT}

---
*Generated by [pr-creator hook](.github/hooks/pr-creator/)*
EOF
)"
fi

# ---------------------------------------------------------------------------
# Create the pull request
# ---------------------------------------------------------------------------

EXTRA_FLAGS=()
if [[ "${PR_DRAFT:-false}" == "true" ]]; then
  EXTRA_FLAGS+=("--draft")
fi

log "🔀 Creating PR: '${CURRENT_BRANCH}' → '${BASE_BRANCH}'..."

PR_URL=$(gh pr create \
  --base "$BASE_BRANCH" \
  --head "$CURRENT_BRANCH" \
  --title "$PR_TITLE" \
  --body "$PR_BODY" \
  "${EXTRA_FLAGS[@]}" 2>&1) || {
  warn "Failed to create PR: $PR_URL"
  exit 1
}

log "✅ Pull request created: ${PR_URL}"
